version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "8081:8080" # Changed from 8080:8080
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - auth-service
      - user-service
      - product-service
      - cart-service
      - order-service
    volumes:
      - ./monitoring:/app/monitoring

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql-db
    volumes:
      - ./monitoring:/app/monitoring

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql-db
    volumes:
      - ./monitoring:/app/monitoring

  product-service:
    build: ./product-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
    volumes:
      - ./monitoring:/app/monitoring
      - product-uploads:/app/uploads
    depends_on:
      - mysql-db

  cart-service:
    build: ./cart-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
    depends_on:
      - mysql-db
    volumes:
      - ./monitoring:/app/monitoring

  order-service:
    build: ./order-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
    depends_on:
      - mysql-db
    volumes:
      - ./monitoring:/app/monitoring

  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  mysql-data:
  product-uploads:
