global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['localhost:3001']

  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:3002']

  - job_name: 'product-service'
    static_configs:
      - targets: ['localhost:3003']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['localhost:3004']

  - job_name: 'order-service'
    static_configs:
      - targets: ['localhost:3005']
