name = "ecommerce-cf-worker"
main = "src/index.js"
compatibility_date = "2023-10-02"

# Configure environment variables
[vars]
API_GATEWAY_URL = "http://localhost:3010"

# KV Namespace for caching
[[kv_namespaces]]
binding = "cache_namespace"
id = "b95ac6a9460543aeb0f79e4509de8dfe"
preview_id = "cache-namespace-preview"


